image: golang:1.21

stages:
  - test
  - release

test:
  stage: test
  script:
    - export BUNDLE_GEMFILE=$PWD/testdata/Gemfile
    - export PATH=$PATH:$PWD/dita-ot-3.6/bin:$PWD/bin

    - apt-get -qq update
    - apt-get install -y curl gnupg build-essential default-jre
    - apt-get install -y xsltproc zip unzip python3-pip ruby-full

    - apt install -y python3-sphinx
    - gem install asciidoctor bundler

    - wget https://github.com/dita-ot/dita-ot/releases/download/3.6/dita-ot-3.6.zip
    - unzip dita-ot-3.6.zip > /dev/null 2>&1
    - which dita
    - dita -h

    - make setup
    - make build os=linux exe=vale
    - make test
