image: golang:1.15

stages:
  - test

test:
  stage: test
  script:
    - export BUNDLE_GEMFILE=$PWD/Gemfile
    - export PATH=$PATH:$PWD/dita-ot-3.6/bin

    - apt-get -qq update
    - apt-get install -y curl gnupg build-essential default-jre
    - apt-get install -y xsltproc zip unzip python-pip ruby-full

    - pip install sphinx
    - gem install asciidoctor bundler

    # NOTE: This is just for testing purposes -- we want to ensure that
    # GoDownloader is working.
    - curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s latest

    - wget https://github.com/dita-ot/dita-ot/releases/download/3.6/dita-ot-3.6.zip
    - unzip dita-ot-3.6.zip > /dev/null 2>&1
    - which dita
    - dita -h

    - make setup
    - make build os=linux exe=vale
    - make test

# TODO: Add deploy stage ...
