dist: xenial
sudo: required
language: python
python: 3.7
before_install:
  - cd docs
install:
  - go get github.com/errata-ai/vale
  - go get github.com/olekukonko/tablewriter
  - pip install pipenv
  - gem install awesome_bot
script:
  - pipenv sync
  # - go run api.go
  - vale content
  - awesome_bot --allow-dupe --allow-redirect content/*.md
after_success:
  # Build our data sources:
  - markdata --directives='content/directives' content
  # Build our site:
  - mkdocs build --verbose --clean
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/site
  on:
    branch: master

