dist: trusty
sudo: required
language: go
go:
  - 1.7
  - 1.8
  - 1.9
before_install:
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - export TRAVIS_RUBY_VERSION="$(ruby -e 'puts RUBY_VERSION')-travis"
  - export PATH=~/bin:"$PATH"
  - pip install --user docutils
  - gem install asciidoctor
install:
  - make setup
  - make build
script:
  - make test
after_script:
  - make compare
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
