dist: xenial
sudo: required
language: go
services:
  - docker
go:
  - 1.15.x

before_install:
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - export TRAVIS_RUBY_VERSION="$(ruby -e 'puts RUBY_VERSION')-travis"
  - export PATH=$PATH:~/bin:$PWD/dita-ot-3.6/bin/

  # NOTE: This is just for testing purposes -- we want to ensure that
  # GoDownloader is working.
  - curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s latest

  - wget https://github.com/dita-ot/dita-ot/releases/download/3.6/dita-ot-3.6.zip
  - unzip dita-ot-3.6.zip > /dev/null 2>&1

  - sudo apt-get install -y xsltproc
  - pip install --user sphinx
  - gem update --system
  - gem install asciidoctor
  - cat $(which asciidoctor)
  - echo $GEM_PATH
  - echo $GEM_HOME

install:
  - make setup
  -  # FIXME: make rules
  - make build os=linux exe=vale

script:
  - make test

after_success:
  - git stash --include-untracked
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
