version: "{build}"
os: Windows Server 2012 R2
clone_folder: c:\GOPATH\src\github.com\errata-ai\vale
environment:
  GOPATH: c:\GOPATH
init:
  - cmd: set PATH=C:\MinGW\bin;%PATH%
  - cmd: copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\Ruby24\bin;%cd%;%PATH%
  - cinst ansicon

  - pip install sphinx
  - gem install asciidoctor

  - choco install xsltproc
  # Git on AppVeyor includes a non-functional xsltproc. Remove this.
  - if exist "%ProgramFiles%\Git\usr\bin\xsltproc.exe" del "%ProgramFiles%\Git\usr\bin\xsltproc.exe"

  - curl -fsSL -o C:\dita-ot-3.4.zip https://github.com/dita-ot/dita-ot/releases/download/3.4/dita-ot-3.4.zip
  - 7z x C:\dita-ot-3.4.zip -y -r -oC:\dita
  - set PATH=C:\dita\dita-ot-3.4\bin;%PATH%
build_script:
  - cmd: make setup
  - cmd: make build os=windows exe=vale.exe
test_script:
  - cmd: make test

# after_test:
#   - cmd: make compare
