site_name: 'Your style, our Editor'
site_description: A customizable, syntax-aware linter for prose.
site_author: Joseph Kato
site_url: https://errata-ai.github.io/vale/

# Repository
repo_name: errata-ai/vale
repo_url: https://github.com/errata-ai/vale
docs_dir: content
edit_uri: edit/master/docs/content/

# Copyright
copyright: 'Copyright &copy; 2016 - 2019 Joseph Kato'

nav:
- Getting Started: index.md
- Usage: usage.md
- Configuration: config.md
- Markup: formats.md
- Styles: styles.md
- Plugins: plugins.md
- Examples: examples.md

theme:
  name: material
  favicon: 'img/vale.png'
  logo: 'img/vale.png'
  palette:
    primary: 'white'
    accent: 'light blue'

extra_css:
  - 'css/style.css'
  - 'css/quickstart.css'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'
  - 'js/quickstart.min.js'
  - 'js/install.js'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      check_paths: true
      base_path: 'content'
